[jenkins]
192.168.56.10 ansible_user=vagrant ansible_ssh_pass=vagrant

[k8s]
192.168.56.20 ansible_user=vagrant ansible_ssh_pass=vagrant

[monitoring]
192.168.56.30 ansible_user=vagrant ansible_ssh_pass=vagrant

[all:vars]
ansible_python_interpreter=/usr/bin/python3
